Remove degree symbol from testcase comment.
I had used the degree symbol in a unit test comment.
That causes compilation to give errors like:

src/test/java/frc/robot/subsystems/LimelightTest.java:26:
    error: unmappable character (0xC2) for encoding US-ASCII
    // tan(20?? + 25??) = 1, so this is just targetHeight -
        mountHeight

There seem to be some ways to fix that by getting -encoding
passed to the compiler, but it wasn't immediately obvious
to me how you'd do that ing gradle, so just not worth
spending effort.